### ISSUE TITLE
Drawing is interrupted when multiple people draw with the pen tool at the same time

### ISSUE THREAD

**Issue by satoren** [RahulBadenkal/y-excalidraw#6]
Drawing seems to be interrupted if updates are made via yjs while drawing.

It is difficult to reproduce alone, but it can be confirmed by using the pen tool on two devices at the same time.

**Comment by RahulBadenkal** [comment]
Thanks for pointing it out.
Do you see any errors in console when this happens?

**Comment by satoren** [comment]
No errors.
The reason is that all elements are updated here.

https://github.com/RahulBadenkal/y-excalidraw/blob/43150ca3d8a3ef703da2c8a857ae76cc9e69e25a/src/index.ts#L72-L80

Excalidraw aborts the change when the element being changed is replaced.
My previous implementation had the same problem, so I had to update only the elements that had changed.

**Comment by RahulBadenkal** [comment]
Oh, got it

**Comment by satoren** [comment]
fixed https://github.com/RahulBadenkal/y-excalidraw/pull/7
